/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 geotermicaOne.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/geotermicaOne.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Line221.geometry} material={materials['Tuberia.002']} position={[-0.63, -0.37, 0.076]} rotation={[0, -1.568, 0]} scale={0.01} />
      <mesh geometry={nodes.Line002.geometry} material={materials['Base central.001']} position={[0.112, 0.281, 0.128]} scale={0.006} />
      <mesh geometry={nodes.Line098.geometry} material={materials['Base central.001']} position={[0.086, 0.281, -0.104]} rotation={[0, 0.457, 0]} scale={0.006} />
      <mesh geometry={nodes.Line139.geometry} material={materials['Base central.001']} position={[-0.101, 0.281, -0.086]} rotation={[-Math.PI, 0.475, -Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Line180.geometry} material={materials['Base central.001']} position={[-0.112, 0.281, 0.151]} rotation={[Math.PI, 0, Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials['tuerca redonda.001']} position={[0.182, 0.399, 0.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials['tuerca redonda.001']} position={[0.154, 0.399, -0.124]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.01} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials['tuerca redonda.001']} position={[-0.158, 0.399, -0.129]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.01} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials['tuerca redonda.001']} position={[-0.182, 0.399, 0.138]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials['tuerca hexagonal.001']} position={[0.183, 0.399, 0.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.01, 0.013, 0.01]} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials['tuerca hexagonal.001']} position={[0.155, 0.399, -0.124]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.01, 0.013, 0.01]} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials['tuerca hexagonal.001']} position={[-0.159, 0.399, -0.129]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.01, 0.013, 0.01]} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials['tuerca hexagonal.001']} position={[-0.183, 0.399, 0.138]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.01, 0.013, 0.01]} />
      <mesh geometry={nodes.Box001.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, 0.19, 0.198]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box002.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, 0.021, 0.198]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box003.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, -0.148, 0.198]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box004.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, -0.316, 0.198]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box005.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, 0.19, 0.081]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box006.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, 0.021, 0.081]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box007.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, -0.148, 0.081]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box008.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.177, -0.316, 0.081]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box036.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.175, 0.19, -0.069]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box037.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.175, 0.021, -0.069]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box038.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.175, -0.148, -0.069]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box039.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.175, -0.316, -0.069]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box040.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.123, 0.19, -0.174]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box041.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.123, 0.021, -0.174]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box042.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.123, -0.148, -0.174]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box043.geometry} material={materials['Cuadrado sujecion metales.001']} position={[0.123, -0.316, -0.174]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.014} />
      <mesh geometry={nodes.Box045.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.126, 0.19, -0.179]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box046.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.126, 0.021, -0.179]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box047.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.126, -0.148, -0.179]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box048.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.126, -0.316, -0.179]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box049.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.18, 0.19, -0.074]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box050.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.18, 0.021, -0.074]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box051.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.18, -0.148, -0.074]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box052.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.18, -0.316, -0.074]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.014} />
      <mesh geometry={nodes.Box054.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, 0.19, 0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box055.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, 0.021, 0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box056.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, -0.148, 0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box057.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, -0.316, 0.08]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box058.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, 0.19, 0.198]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box059.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, 0.021, 0.198]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box060.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, -0.148, 0.198]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Box061.geometry} material={materials['Cuadrado sujecion metales.001']} position={[-0.177, -0.316, 0.198]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.014} />
      <mesh geometry={nodes.Line004.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.212, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line060.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.236, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line061.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.259, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line062.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.283, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line063.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.047, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line065.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.071, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line066.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.094, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line067.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.118, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line068.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.13, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line070.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.106, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line071.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.083, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line072.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.059, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line073.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.295, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line075.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.271, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line076.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.248, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line077.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.224, 0.198]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line078.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.212, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line080.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.236, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line081.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.259, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line082.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.283, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line083.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.047, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line085.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.071, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line086.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.094, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line087.geometry} material={materials['Bara cobre.001']} position={[0.343, 0.118, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line088.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.13, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line090.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.106, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line091.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.083, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line092.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.059, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line093.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.295, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line095.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.271, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line096.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.248, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line097.geometry} material={materials['Bara cobre.001']} position={[0.343, -0.224, 0.08]} rotation={[Math.PI / 2, 0.061, 0]} scale={0.01} />
      <mesh geometry={nodes.Line099.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.212, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line101.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.236, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line102.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.259, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line103.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.283, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line104.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.047, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line106.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.071, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line107.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.094, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line108.geometry} material={materials['Bara cobre.001']} position={[0.324, 0.118, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line109.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.13, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line111.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.106, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line112.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.083, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line113.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.059, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line114.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.295, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line116.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.271, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line117.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.248, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line118.geometry} material={materials['Bara cobre.001']} position={[0.324, -0.224, -0.143]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line119.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.212, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line121.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.236, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line122.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.259, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line123.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.283, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line124.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.047, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line126.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.071, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line127.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.094, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line128.geometry} material={materials['Bara cobre.001']} position={[0.272, 0.118, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line129.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.13, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line131.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.106, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line132.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.083, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line133.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.059, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line134.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.295, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line136.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.271, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line137.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.248, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line138.geometry} material={materials['Bara cobre.001']} position={[0.272, -0.224, -0.249]} rotation={[1.598, 0.054, -0.457]} scale={0.01} />
      <mesh geometry={nodes.Line140.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.212, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line142.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.236, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line143.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.259, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line144.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.283, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line145.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.047, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line147.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.071, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line148.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.094, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line149.geometry} material={materials['Bara cobre.001']} position={[-0.274, 0.118, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line150.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.13, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line152.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.106, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line153.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.083, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line154.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.059, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line155.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.295, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line157.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.271, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line158.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.248, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line159.geometry} material={materials['Bara cobre.001']} position={[-0.274, -0.224, -0.254]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line160.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.212, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line162.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.236, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line163.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.259, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line164.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.283, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line165.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.047, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line167.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.071, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line168.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.094, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line169.geometry} material={materials['Bara cobre.001']} position={[-0.328, 0.118, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line170.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.13, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line172.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.106, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line173.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.083, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line174.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.059, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line175.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.295, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line177.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.271, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line178.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.248, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line179.geometry} material={materials['Bara cobre.001']} position={[-0.328, -0.224, -0.149]} rotation={[1.599, -0.054, -2.666]} scale={0.01} />
      <mesh geometry={nodes.Line181.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.212, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line183.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.236, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line184.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.259, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line185.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.283, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line186.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.047, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line188.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.071, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line189.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.094, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line190.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.118, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line191.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.13, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line193.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.106, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line194.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.083, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line195.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.059, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line196.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.295, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line198.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.271, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line199.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.248, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line200.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.224, 0.081]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line201.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.212, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line203.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.236, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line204.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.259, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line205.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.283, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line206.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.047, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line208.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.071, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line209.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.094, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line210.geometry} material={materials['Bara cobre.001']} position={[-0.343, 0.118, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line211.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.13, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line213.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.106, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line214.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.083, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line215.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.059, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line216.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.295, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line218.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.271, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line219.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.248, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line220.geometry} material={materials['Bara cobre.001']} position={[-0.343, -0.224, 0.198]} rotation={[Math.PI / 2, -0.061, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line005.geometry} material={materials['Metales.002']} position={[0.226, 0.214, 0.198]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line064.geometry} material={materials['Metales.002']} position={[0.226, 0.05, 0.198]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line069.geometry} material={materials['Metales.002']} position={[0.226, -0.128, 0.198]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line074.geometry} material={materials['Metales.002']} position={[0.226, -0.292, 0.198]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line079.geometry} material={materials['Metales.002']} position={[0.226, 0.214, 0.08]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line084.geometry} material={materials['Metales.002']} position={[0.226, 0.05, 0.08]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line089.geometry} material={materials['Metales.002']} position={[0.226, -0.128, 0.08]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line094.geometry} material={materials['Metales.002']} position={[0.226, -0.292, 0.08]} rotation={[Math.PI / 2, 0.396, 0]} scale={0.01} />
      <mesh geometry={nodes.Line100.geometry} material={materials['Metales.002']} position={[0.219, 0.214, -0.091]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line105.geometry} material={materials['Metales.002']} position={[0.219, 0.05, -0.091]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line110.geometry} material={materials['Metales.002']} position={[0.219, -0.128, -0.091]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line115.geometry} material={materials['Metales.002']} position={[0.219, -0.292, -0.091]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line120.geometry} material={materials['Metales.002']} position={[0.167, 0.214, -0.197]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line125.geometry} material={materials['Metales.002']} position={[0.167, 0.05, -0.197]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line130.geometry} material={materials['Metales.002']} position={[0.167, -0.128, -0.197]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line135.geometry} material={materials['Metales.002']} position={[0.167, -0.292, -0.197]} rotation={[1.753, 0.353, -0.489]} scale={0.01} />
      <mesh geometry={nodes.Line141.geometry} material={materials['Metales.002']} position={[-0.17, 0.214, -0.2]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line146.geometry} material={materials['Metales.002']} position={[-0.17, 0.05, -0.2]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line151.geometry} material={materials['Metales.002']} position={[-0.17, -0.128, -0.2]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line156.geometry} material={materials['Metales.002']} position={[-0.17, -0.292, -0.2]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line161.geometry} material={materials['Metales.002']} position={[-0.224, 0.214, -0.095]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line166.geometry} material={materials['Metales.002']} position={[-0.224, 0.05, -0.095]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line171.geometry} material={materials['Metales.002']} position={[-0.224, -0.128, -0.095]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line176.geometry} material={materials['Metales.002']} position={[-0.224, -0.292, -0.095]} rotation={[1.76, -0.35, -2.633]} scale={0.01} />
      <mesh geometry={nodes.Line182.geometry} material={materials['Metales.002']} position={[-0.226, 0.214, 0.081]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line187.geometry} material={materials['Metales.002']} position={[-0.226, 0.05, 0.081]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line192.geometry} material={materials['Metales.002']} position={[-0.226, -0.128, 0.081]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line197.geometry} material={materials['Metales.002']} position={[-0.226, -0.292, 0.081]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line202.geometry} material={materials['Metales.002']} position={[-0.226, 0.214, 0.198]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line207.geometry} material={materials['Metales.002']} position={[-0.226, 0.05, 0.198]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line212.geometry} material={materials['Metales.002']} position={[-0.226, -0.128, 0.198]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Line217.geometry} material={materials['Metales.002']} position={[-0.226, -0.292, 0.198]} rotation={[Math.PI / 2, -0.396, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Box033.geometry} material={materials['Material.005']} position={[0.179, -0.039, 0.139]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Box044.geometry} material={materials['Material.005']} position={[0.151, -0.039, -0.124]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.01} />
      <mesh geometry={nodes.Box053.geometry} material={materials['Material.005']} position={[-0.156, -0.039, -0.126]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.01} />
      <mesh geometry={nodes.Box062.geometry} material={materials['Material.005']} position={[-0.179, -0.039, 0.14]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Tornillo .001']} position={[0.16, 0.422, 0.116]} rotation={[Math.PI / 2, 0, -2.042]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Tornillo .001']} position={[0.183, 0.308, 0.158]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Tornillo .001']} position={[0.183, 0.135, 0.12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Tornillo .001']} position={[0.183, 0.135, 0.158]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Tornillo .001']} position={[0.183, -0.038, 0.12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Tornillo .001']} position={[0.183, -0.038, 0.158]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Tornillo .001']} position={[0.183, -0.211, 0.12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials['Tornillo .001']} position={[0.183, -0.211, 0.158]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials['Tornillo .001']} position={[0.183, -0.384, 0.12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['Tornillo .001']} position={[0.183, -0.384, 0.158]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials['Tornillo .001']} position={[0.16, 0.317, 0.116]} rotation={[Math.PI / 2, 0, -2.042]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials['Tornillo .001']} position={[0.16, 0.326, 0.116]} rotation={[Math.PI / 2, 0, -2.042]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials['Tornillo .001']} position={[0.16, 0.422, 0.162]} rotation={[-Math.PI / 2, 0, 1.099]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials['Tornillo .001']} position={[0.16, 0.317, 0.162]} rotation={[-Math.PI / 2, 0, 1.099]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere015.geometry} material={materials['Tornillo .001']} position={[0.16, 0.326, 0.162]} rotation={[-Math.PI / 2, 0, 1.099]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials['Tornillo .001']} position={[0.124, 0.422, -0.136]} rotation={[Math.PI / 2, 0, -2.499]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere018.geometry} material={materials['Tornillo .001']} position={[0.163, 0.308, -0.108]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere019.geometry} material={materials['Tornillo .001']} position={[0.146, 0.135, -0.142]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere020.geometry} material={materials['Tornillo .001']} position={[0.163, 0.135, -0.108]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere021.geometry} material={materials['Tornillo .001']} position={[0.146, -0.038, -0.142]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere022.geometry} material={materials['Tornillo .001']} position={[0.163, -0.038, -0.108]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere023.geometry} material={materials['Tornillo .001']} position={[0.146, -0.211, -0.142]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere024.geometry} material={materials['Tornillo .001']} position={[0.163, -0.211, -0.108]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere025.geometry} material={materials['Tornillo .001']} position={[0.146, -0.384, -0.142]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere026.geometry} material={materials['Tornillo .001']} position={[0.163, -0.384, -0.108]} rotation={[Math.PI / 2, 0, -2.028]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere027.geometry} material={materials['Tornillo .001']} position={[0.124, 0.317, -0.136]} rotation={[Math.PI / 2, 0, -2.499]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere028.geometry} material={materials['Tornillo .001']} position={[0.124, 0.326, -0.136]} rotation={[Math.PI / 2, 0, -2.499]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere029.geometry} material={materials['Tornillo .001']} position={[0.144, 0.422, -0.094]} rotation={[-Math.PI / 2, 0, 1.556]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere030.geometry} material={materials['Tornillo .001']} position={[0.144, 0.317, -0.094]} rotation={[-Math.PI / 2, 0, 1.556]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere031.geometry} material={materials['Tornillo .001']} position={[0.144, 0.326, -0.094]} rotation={[-Math.PI / 2, 0, 1.556]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere033.geometry} material={materials['Tornillo .001']} position={[-0.149, 0.422, -0.097]} rotation={[Math.PI / 2, 0, 1.574]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere034.geometry} material={materials['Tornillo .001']} position={[-0.151, 0.308, -0.145]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere035.geometry} material={materials['Tornillo .001']} position={[-0.168, 0.135, -0.111]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere036.geometry} material={materials['Tornillo .001']} position={[-0.151, 0.135, -0.145]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere037.geometry} material={materials['Tornillo .001']} position={[-0.168, -0.038, -0.111]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere038.geometry} material={materials['Tornillo .001']} position={[-0.151, -0.038, -0.145]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere039.geometry} material={materials['Tornillo .001']} position={[-0.168, -0.211, -0.111]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere040.geometry} material={materials['Tornillo .001']} position={[-0.151, -0.211, -0.145]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere041.geometry} material={materials['Tornillo .001']} position={[-0.168, -0.384, -0.111]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere042.geometry} material={materials['Tornillo .001']} position={[-0.151, -0.384, -0.145]} rotation={[Math.PI / 2, 0, 2.046]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere043.geometry} material={materials['Tornillo .001']} position={[-0.149, 0.317, -0.097]} rotation={[Math.PI / 2, 0, 1.574]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere044.geometry} material={materials['Tornillo .001']} position={[-0.149, 0.326, -0.097]} rotation={[Math.PI / 2, 0, 1.574]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere045.geometry} material={materials['Tornillo .001']} position={[-0.128, 0.422, -0.139]} rotation={[-Math.PI / 2, 0, -2.517]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere046.geometry} material={materials['Tornillo .001']} position={[-0.128, 0.317, -0.139]} rotation={[-Math.PI / 2, 0, -2.517]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere047.geometry} material={materials['Tornillo .001']} position={[-0.128, 0.326, -0.139]} rotation={[-Math.PI / 2, 0, -2.517]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere049.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.422, 0.163]} rotation={[Math.PI / 2, 0, 1.099]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere050.geometry} material={materials['Tornillo .001']} position={[-0.183, 0.308, 0.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere051.geometry} material={materials['Tornillo .001']} position={[-0.183, 0.135, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere052.geometry} material={materials['Tornillo .001']} position={[-0.183, 0.135, 0.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere053.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.038, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere054.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.038, 0.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere055.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.211, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere056.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.211, 0.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere057.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.384, 0.159]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere058.geometry} material={materials['Tornillo .001']} position={[-0.183, -0.384, 0.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere059.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.317, 0.163]} rotation={[Math.PI / 2, 0, 1.099]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere060.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.326, 0.163]} rotation={[Math.PI / 2, 0, 1.099]} scale={[0.006, 0.003, 0.006]} />
      <mesh geometry={nodes.Sphere061.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.422, 0.116]} rotation={[-Math.PI / 2, 0, -2.042]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere062.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.317, 0.116]} rotation={[-Math.PI / 2, 0, -2.042]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere063.geometry} material={materials['Tornillo .001']} position={[-0.16, 0.326, 0.116]} rotation={[-Math.PI / 2, 0, -2.042]} scale={[-0.006, -0.003, -0.006]} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials['Pegamento tornillo .001']} position={[0.163, 0.399, 0.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Sphere032.geometry} material={materials['Pegamento tornillo .001']} position={[0.137, 0.399, -0.115]} rotation={[Math.PI / 2, 0, -2.028]} scale={0.01} />
      <mesh geometry={nodes.Sphere048.geometry} material={materials['Pegamento tornillo .001']} position={[-0.141, 0.399, -0.12]} rotation={[Math.PI / 2, 0, 2.046]} scale={0.01} />
      <mesh geometry={nodes.Sphere064.geometry} material={materials['Pegamento tornillo .001']} position={[-0.163, 0.399, 0.138]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Pegamento tornillo .001']} position={[0.115, 0.302, 0.139]} scale={0.01} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Pegamento tornillo .001']} position={[0.094, 0.302, -0.095]} rotation={[0, 0.457, 0]} scale={0.01} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Pegamento tornillo .001']} position={[-0.099, 0.302, -0.097]} rotation={[-Math.PI, 0.475, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['Pegamento tornillo .001']} position={[-0.115, 0.302, 0.139]} rotation={[Math.PI, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Aset_rock_cliffs_M_ubvsaf3da_LOD0.geometry} material={materials['suelo.002']} position={[0.027, -0.513, 0.024]} rotation={[Math.PI / 2, 0, 0.099]} scale={0.022} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Cono superior.001']} position={[0.115, 0.293, 0.139]} scale={0.01} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials['Cono superior.001']} position={[0.094, 0.293, -0.095]} rotation={[0, 0.457, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials['Cono superior.001']} position={[-0.099, 0.293, -0.098]} rotation={[-Math.PI, 0.475, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials['Cono superior.001']} position={[-0.115, 0.293, 0.139]} rotation={[Math.PI, 0, Math.PI]} scale={0.01} />
      <group position={[-1.465, -0.482, 0.253]} rotation={[Math.PI, -1.561, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh033.geometry} material={materials['caja.003']} />
        <mesh geometry={nodes.Mesh033_1.geometry} material={materials['Tapa.003']} />
        <mesh geometry={nodes.Mesh033_2.geometry} material={materials['union.003']} />
      </group>
      <mesh geometry={nodes.Arc001.geometry} material={materials['Base cilindro.002']} position={[0.014, -0.44, 0.03]} rotation={[Math.PI, -1.561, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Box063.geometry} material={materials['Material.006']} position={[-1.459, -0.385, 0.041]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/geotermicaOne.gltf')
