export const referenciaGeo1 =
  "Imagen de 3D WareHouse, disponible en https://3dwarehouse.sketchup.com/model/791bdfed-cadc-4ec9-b4b2-f0c32b97582a/Energ%C3%ADa-Geot%C3%A9rmica";

export const referenciaGeo2 =
  "Imagen de 3D WareHouse, disponible en https://3dwarehouse.sketchup.com/model/udae01287-f738-47b4-a1f8-abda33158d2e/industria-geot%C3%A9rmica";

// Textos información energía Eólica
export const eolicInfoOne =
  "La energía eólica terrestre, se refiere a la energía generada a partir del viento en tierra firme. Esta forma de energía renovable se produce mediante el uso de aerogeneradores que convierten la energía cinética del viento en electricidad. Su uso no emite gases de efecto invernadero ni produce residuos peligrosos, por lo que se trata de una energía limpia, renovable e inagotable. Costa Rica cuenta con 18 parques eólicos que albergan un total de 343 turbinas. La mayoría de estas plantas son privadas, y solo existe una planta estatal llamada Planta Eólica Tejona, ubicada en Tilarán de Guanacaste. El potencial eólico del país se estima en 2,400 MW de capacidad instalable, con una producción anual de energía de 6,700 GWh1. Algunos de los proyectos eólicos en desarrollo incluyen:\n1.Orosí\n2.Campos Azules\n3.Altamira\n4.Vientos de la Perla\n5.Vientos de Miramar";
// Texto energía Eólica Plus
export const eolicInfoTwo =
  "Las turbinas eólicas terrestres funcionan capturando y convirtiendo la energía cinética del viento en energía eléctrica utilizable. Su funcionamiento comienza en el rotor, formado por varias palas, cuya tarea es recoger el viento a medida que sopla, provocando la rotación necesaria para generar electricidad. Un generador eléctrico situado en lo alto de la torre convierte este movimiento en energía eléctrica. Finalmente, la energía fluye a través del sistema de cables hasta el transformador, que se encarga de aumentar el voltaje de la electricidad resultante para su transporte a través de la red eléctrica de alto voltaje.";
// Texto Card Uno Eólica
export const cardEolicOne =
  "Esta energía tiene impactos socioeconómicos positivos en las comunidades locales y la economía en general, ya que la construcción, instalación y mantenimiento de turbinas eólicas requieren una gran cantidad de mano de obra, lo que genera más empleos en los sectores industrial, manufacturero, de ingeniería y de servicios. Además, esta energía puede ayudar a reducir la dependencia energética de la región de los combustibles fósiles y mejorar la seguridad energética.";
// Texto Card Dos Eólica
export const cardEolicTwo =
  "El impacto medioambiental de la energía eólica terrestre es relativamente bajo en comparación con otras fuentes de energía porque no produce emisiones de gases de efecto invernadero (GEI). Es una energía limpia y renovable que puede ayudar a contrarrestar el calentamiento global. Por otro lado, hay que tener en cuenta los efectos visuales sobre el paisaje y los efectos acústicos a distancias cortas.";

// Textos información energía Geotérmica
export const geotermicInfoOne =
  "La energía geotérmica procede del aprovechamiento del calor de la Tierra. Las condiciones geológicas de las islas Canarias ofrecen un gran potencial para poder desarrollar este tipo de energía. Una de las mayores ventajas sobre otros tipos de energías renovables es que es constante y prácticamente inagotable si es bien aprovechada. Algunos detalles interesantes:\n1.Planta geotérmica de Las Pailas: \n✅Ubicada en la ladera del volcán Rincón de la Vieja, en el norte del país.\n✅Tiene una capacidad de 35 MW y comenzó a funcionar en julio de 2011.\n✅Se están evaluando dos nuevos proyectos geotérmicos en la misma región: Las Pailas II y Borinquen, cada uno con una capacidad potencial de hasta 50 MW1.\n2.Potencial geotérmico de Costa Rica:\n✅Se concentra en la Cordillera Volcánica Central y la de Guanacaste.\n✅Se estima que el potencial geotérmico del país está entre 865 y 1,100 MW1.\n3.Contribución a la producción energética:\n✅El Grupo ICE (Instituto Costarricense de Electricidad) opera una red de plantas geotérmicas en las faldas de los volcanes Miravalles, Rincón de la Vieja y Tenorio en la provincia de Guanacaste.\n✅Estas plantas generan más del 13% de la electricidad total del país";

export const geotermicInfoTwo =
  "La energía geotérmica capta el calor existente bajo tierra, generado por rocas fundidas, minerales y gases en diferentes capas. El agua de lluvia que se filtra a través de la corteza terrestre forma corrientes de agua profundas y acuíferos confinados, que, a su vez, al entrar en contacto con el subsuelo a altas temperaturas, forman vapor y agua, creando una reserva geotérmica.";

// Texto Card Uno Geotérmica
export const cardGeotermicOne =
  "Es uno de los sistemas renovables de calentamiento de agua, calefacción y aire acondicionado más eficientes y rentables, ya que utiliza alrededor de un 75% menos que los sistemas tradicionales. Como ocurre con otras energías renovables, su desarrollo beneficia a las economías locales de las islas mediante la creación de nuevos negocios y empleos.";
// Texto Card Dos Geotérmica
export const cardGeotermicTwo =
  "Los beneficios se notan al ser una energía 100% renovable, limpia e inagotable y una de las energías verdes de mayor crecimiento a nivel internacional. La mayoría de las desventajas frente a otros tipos de fuentes de energía renovables surgen durante la instalación de los sistemas, ya que pueden requerir grandes inversiones y altos niveles de contaminación acústica durante la perforación.";

// Textos información energía Solar
export const solarInfoOne =
  "La energía solar fotovoltaica es una fuente de energía renovable y limpia que convierte la radiación solar en energía eléctrica mediante el efecto fotovoltaico. Este proceso se lleva a cabo mediante paneles compuestos por diferentes materiales que pueden absorber fotones y emitir electrones para producir electricidad. Más detalles:\n1.Tipo de energía más utilizada:\n🟦A pesar de ser reconocido por su compromiso con las energías renovables, hasta hace poco, la principal fuente de energía en Costa Rica ha sido la hidroeléctrica. Gracias a su abundancia de ríos y lluvias, Costa Rica ha aprovechado la energía hidráulica para generar electricidad de manera sostenible durante décadas.\n🟦Sin embargo, en los últimos años, la energía solar ha ganado terreno como una importante alternativa para diversificar la matriz energética del país y reducir su dependencia de combustibles fósiles.\n2.Costo de 1 KW de energía solar:\n🟦El costo de 1 kilovatio (KW) de energía solar en Costa Rica puede variar según diversos factores, como el tamaño del sistema, la ubicación geográfica, la eficiencia de los paneles solares y los componentes adicionales necesarios para el funcionamiento del sistema.\n🟦Aunque los precios de los sistemas solares han disminuido significativamente en los últimos años debido a avances tecnológicos y políticas favorables, es esencial considerar que una inversión en energía solar puede tener un retorno a largo plazo al reducir los costos de electricidad a lo largo de su vida útil.\n3.Crecimiento y adopción:\n🟦Costa Rica ha experimentado un aumento en el número de paneles solares instalados en los últimos años. A medida que la conciencia sobre la importancia de la energía solar y la sostenibilidad ha ido en aumento, más hogares, empresas e instituciones han optado por instalar sistemas de energía solar fotovoltaica en sus instalaciones.\n🟦Si bien no hay un número exacto de paneles solares en todo el país, se estima que el crecimiento en la adopción de esta tecnología continúa en ascenso.";

export const solarInfoTwo =
  "Varios módulos fotovoltaicos o placas conectadas entre sí generarían un campo solar, transformando la energía solar en una corriente eléctrica, denominada corriente continua. Colocar paneles solares en el tejado de una casa aporta muchos beneficios, tanto a nivel económico como medioambiental. Al colocar paneles en áreas expuestas a la luz solar directa y ajustar su ángulo de inclinación según la latitud local, se puede maximizar la recolección de energía solar.";

// Texto Card Uno Solar
export const cardSolarOne =
  "Esta fuente de energía eléctrica es una de las más económicas y ayuda a reducir la pobreza energética. Disponer de placas solares para consumo propio tiene un impacto directo en la economía familiar porque se obtiene una importante reducción en las facturas. También son adecuados para proporcionar acceso a electricidad en zonas rurales o lugares remotos, donde la instalación de líneas eléctricas es costosa o difícil.";

// Texto Card Dos Solar
export const cardSolarTwo =
  "La energía fotovoltaica es 100% renovable, no contaminante e inagotable y sus instalaciones pueden durar una media de 30 años, contribuyendo así a las políticas de transición ecológica y al desarrollo sostenible. El impacto medioambiental de esta tecnología es mucho menor que el de otras fuentes de energía convencionales, porque todos los componentes son reciclables y por la integración arquitectónica de paneles solares o módulos fotovoltaicos.";

// Textos información energía Solar
export const hidroInfoOne =
  "A lo largo de la historia, la fuerza cinética del agua se ha utilizado para obtener energía. La energía hidráulica es la energía que se obtiene del aprovechamiento potencial de un flujo de agua. La conversión en energía se puede realizar mediante la instalación de centrales hidroeléctricas, que son capaces de utilizar entre el 90 y el 95% de la energía potencial del agua. La potencia de estas centrales eléctricas puede variar mucho, desde microcentrales, minicentrales hidráulicas hasta centrales eléctricas de pequeña escala o centrales eléctricas de alta potencia. \nLa energía hidroeléctrica en Costa Rica, como un río serpenteando entre montañas, fluye con fuerza y propósito. En las profundidades de los valles, las represas se alzan como guardianes silenciosos. Sus muros de concreto contienen la energía contenida en el agua, como un secreto ancestral. Cuando las compuertas se abren, el rugido del río se convierte en electricidad. Las turbinas giran, generando vida en forma de voltios y amperios. Los ríos de Costa Rica, como arterias vitales, alimentan las centrales hidroeléctricas. Los embalses se llenan con la lluvia de las estaciones húmedas, y luego, en los meses secos, liberan su energía almacenada. Las comunidades rurales, como guardianes ancestrales, han luchado contra las represas. Sus voces se alzan como cascadas rebeldes, clamando por la protección de sus ríos sagrados. En Coto Brus, Buenos Aires, Pérez Zeledón y más allá, se resisten al avance de la tecnología, al precio de su tierra y su cultura. El Instituto Costarricense de Electricidad (ICE), como un titán moderno, ha construido una red de centrales hidroeléctricas. Las cuencas de los ríos San Carlos y Reventazón son testigos de su expansión.";

export const hidroInfoTwo =
  "Las centrales hidroeléctricas de embalse se componen de tres partes fundamentales: la central eléctrica donde se genera electricidad, la presa que controla el paso de agua y un depósito donde se acumula el agua.";

// Texto Card Uno Hidroeléctrica
export const cardHidroOne =
  "Una de las grandes ventajas es que permite cubrir los picos de demanda energética porque el agua embalsada se puede usar de manera flexible. La aplicación de energía hidráulica, al igual que otras formas de energías renovables, fomenta la generación de empleos y, aunque requiere una gran inversión para su inicio, los costos de operación son más bajos que los de la energía convencional.";

// Texto Card Dos Hidroeléctrica
export const cardHidroTwo =
  "La energía hidráulica es renovable, limpia y sostenible, lo que significa que no produce desechos contaminantes. Además, contribuye al objetivo del gobierno de disminuir las emisiones de CO2. A pesar de esto, debido principalmente a la construcción de embalses, puede tener un impacto ambiental en los ecosistemas donde se instale. Además, los embalses pueden controlar el caudal de un río para evitar que se vuelva más peligroso. ";
